# Generated by Django 3.2.9 on 2024-08-10 21:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0003_recipelike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipelike',
            unique_together={('user', 'recipe')},
        ),
    ]
