services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: sh -c "python manage.py migrate && python manage.py makesuperuser && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: worker
    command: celery -A config worker --loglevel=info --without-gossip --pool=solo
    depends_on:
      - redis
      - django
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery_beat
    container_name: scheduler
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - django
    env_file:
      - .env

volumes:
  postgres_data:
